### ISSUE TITLE
Output settings

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-qsim-runner#16]
Each exercise should have an output configuration section, that defines what is displayed on the output. I imagine something like the following:

```yml
output:
  records: false
  flags: true
  special_records: true
  memory:
    from: '0001'
    to: 'A03F'
```

Also, each field should have a default, that will be used if the key is not present:

* `records: true`
* `flags: false`
* `special_records: false`
* `memory: false` (or any null-like value that means "it should not be displayed")

The visualization for the special records and the memory should be similar to the record, but using multiple columns for the memory:
![image](https://cloud.githubusercontent.com/assets/1585835/22469265/1314f85e-e7d4-11e6-8325-fdcd3c76df52.png)
