### ISSUE TITLE
Support memory checks on equal postcondition

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-qsim-runner#17]
The equal postcondition should allow both records and memory positions, and check accordingly:

```yml
examples:
- postconditions:
    equal:
      R4: '0001'
      A002: 'FA00'
```

The 'R' prefix of the record name should be enough to distinguish between memory positions and records.
