### ISSUE TITLE
Remove memory and records keys from preconditions

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-qsim-runner#18]
To be consistent with the postconditions, the 'memory' and 'records' keys should disappear, since we can distinguish them from their name (the 'R' prefix for records, the special records well-known names, etc).

A migration of the existing exercises will be necessary, following this example:

**Before**
```yml
examples:
- preconditions:
    memory:
      A023: '0002'
   records:
      R2: '0003'
      R3: '0004'
```

**After**
```yml
examples:
- preconditions:
    A023: '0002'
    R2: '0003'
    R3: '0004'
```

The JSON output sent to QSim should be the same as now:

```json
{
  "id": 0,
  "special_records": {
    "PC": "0000",
    "SP": "FFEF",
    "IR": "0000"
  },
  "flags": {
    "N": 0,
    "Z": 0,
    "V": 0,
    "C": 0
  },
  "records": {
    "R0": "0000",
    "R1": "0000",
    "R2": "0003",
    "R3": "0000",
    "R4": "0004",
    "R5": "0000",
    "R6": "0000",
    "R7": "0000"
  },
  "memory": {
    "A023": "0002"
  }
}
```
