### ISSUE TITLE
Memory test not working: "xxxx should be xxxx, but was"

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mumuki-qsim-runner#26]
The `expected` value is right but the `actual` value does not show, even when the exercise was solved successfully.

After sending `MOV [0x0030], 0x22FE`...

![image](https://user-images.githubusercontent.com/11304439/54764008-bd721b80-4bd5-11e9-9dc4-11ce95ca7517.png)

Exercise is [here](https://mumuki.io/staging/exercises/7378-arquitectura-de-computadoras-memoria-y-buses-lectura-y-escritura). YAML is 
```
examples:
- name: 'Se copia el valor del registro R4 a la posición de memoria 0x0030'
  postconditions:
    equal:
      '0030': '22FF'
output:
  flags: false
  records: true
  special_records: false
  memory:
    from: '0000'
    to: '0100'
```

I'm using `'0030'` because it starts with 00, but I've had it fail with all quotes & no quotes combinations (such as `FFFF: '22FF'`, or even `FFFF: 22FF`).

The test name is a placeholder.
