### ISSUE TITLE
Memory visualization bugs

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mumuki-qsim-runner#28]
First ten memory positions are always visible (`0000-0009`), even when the output settings don't include that range, and the first couple addresses are always written with some stuff that seems to be related to the solution sent (at least the last couple memory positions. The first three always seem to be `A000`, `0002` and `1820`).

The easier solution I'd be happy with is hiding that first line. For example, for the output settings
```
  memory:
    from: '0050'
    to: '0060'
```

it still shows the `0000-0009` addresses

![image](https://user-images.githubusercontent.com/11304439/54766496-1cd22a80-4bda-11e9-8fa4-cd838cb9046c.png)

and in a related bug, the range that should start at `0050` starts at `0057`. Or it *says* that it starts at `0057`... I'm not sure.

The exercise is [here](https://mumuki.io/staging/exercises/7384-arquitectura-de-computadoras-memoria-y-buses-intercambio). YAML is

```
examples:
- name: '...'
  postconditions:
    equal:
      '22FF': 'FFFF'
output:
  flags: false
  records: true
  special_records: false
  memory:
    from: '0050'
    to: '0060'
```
