### ISSUE TITLE
The output settings should probably be set for each test

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mumuki-qsim-runner#29]
```
examples:
- name: '...'
  postconditions:
    equal:
      '22FF': 'FFFF'
- name: '...'
  postconditions:
    equal:
      '22FE': 'FFFF'
output:
  flags: false
  records: true
  special_records: false
  memory:
    from: '0050'
    to: '0060'
```
Right now `output:` is aligned with `examples:`, but they should probably (and ideally) be set for each test, according to the repo's readme. However, aligning it like
```
examples:
- name: '...'
  postconditions:
    equal:
      '22FF': 'FFFF'
  output:
    flags: false
    records: true
    special_records: false
    memory:
      from: '0050'
      to: '0060'
- name: '...'
  postconditions:
    equal:
      '22FE': 'FFFF'
  output:
    flags: false
    records: true
    special_records: false
    memory:
      from: '0050'
      to: '0060'
```
does not work (default output settings are used).
