### ISSUE TITLE
Memory preconditions

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-qsim-runner#5]
Analog to the current approach for records, the teacher should be able to specify arbitrary values to be loaded in memory:

```yml
examples:
- preconditions:
    memory:
      A023: '28E5'
      0002: '0003'
```
